title: Yang Qiu
description: Kean University (WKU)
site_title: 'Yang Qiu'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
email: yangq@kean.edu
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg
url: https://aiunicorn.github.io

# Google Analytics ID
google_analytics: 
