title: Yang Qiu
description: Wenzhou-Kean University (WKU)
site_title: 'Yang Qiu'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
email: yangq@kean.edu

# absolute or relative
profile_picture: assets/images/avatar.png
url: https://aiunicorn.github.io

# Google Analytics ID
google_analytics: 
